FROM python:3.10-alpine3.16
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY Src src
EXPOSE 3000
HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
            CMD curl -f http://localhost:3003/health || exit 1
ENTRYPOINT [ "python", "./src/app/main.py" ]