server:
  port: 8888

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka
##server.port=8082

spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins:
            - "http://127.0.0.1:5173/"
            - "http://localhost:5173/"
            - "http://localhost:3001"
            - "http://127.0.0.1:3001"
            - "http://pokedoc.ngrok.io"
            - "https://pokedoc.ngrok.io"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT

      routes:
      #User Service
      - id: patientservice
        uri: lb://patientservice
        predicates:
        - Path=/patientservice/**
        - Path=/patients/**
      - id: employeeservice
        uri: lb://employeeservice
        predicates:
        - Path=/employeeservice/**
        - Path=/employees/**
        - Path=/doctor/**
      - id: appointmentservice
        uri: lb://appointmentservice
        predicates:
        - Path=/appointmentservice/**
        - Path=/appointments/**
        - Path=/appointment/**